[package]
name = "cross-check-derive"
version = "0.1.0"
authors = ["Andrei Homescu <ah@immunant.com>"]
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
cross-check-config = { path = "../config", features = ["parse-syn", "with-quote"] }
syn = { version = "0.11.11", features = ["full", "visit"] }
synstructure = "0.6.1"
quote = "0.3.15"

[dev-dependencies]
cross-check-runtime = { path = "../runtime" }
